spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-headers: 
              - Content-Type
            exposed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS